SET VERIFY OFF;

SET LINES 1000
SET PAGES 1000

COLUMN EXTENDED_TIMESTAMP FORMAT A15
COLUMN USERNAME FORMAT A6
COLUMN OWNER FORMAT A10
COLUMN obj_name FORMAT A30
COLUMN action_name FORMAT A16
COLUMN PRIV_USED FORMAT A32

SELECT TO_CHAR(EXTENDED_TIMESTAMP, 'MM-DD HH24:MI:SS') as timestamp, username, owner, obj_name, action_name, priv_used FROM DBA_AUDIT_TRAIL where EXTENDED_TIMESTAMP between TO_TIMESTAMP('&1', 'YYYY-MM-DD HH24:MI:SS') - interval '30' second and TO_TIMESTAMP('&2', 'YYYY-MM-DD HH24:MI:SS') + interval '30' second order by timestamp desc ;
exit;
