#!/bin/bash

CLOB=$(cat; echo x)
CLOB=${CLOB%x}
printf %s "$CLOB" | /var/opt/gitlab/git-data/repositories/ano/csas-db-ci.git/hooks/post-receive-gitlab

echo -n "Post receive hook: " >> /tmp/ano_git_log
date >> /tmp/ano_git_log
echo  "Post receive hook CLOB: $CLOB" >> /tmp/ano_git_log

SERVICES_CENTRAL="172.17.0.1"

function start_build() {
    GIT_PROJECT=$1
    BUILD_DELAY=$(curl -s http://${SERVICES_CENTRAL}:8000/GetDelay/$GIT_PROJECT | python3 -c "import sys, json; print(json.load(sys.stdin)['delay'])");
    echo "Post receive hook build delay: $BUILD_DELAY" >> /tmp/ano_git_log;
    if [[ "$BUILD_DELAY" = "0" ]] ; then
        curl -s -k -u anovak:Abcd1234 https://${SERVICES_CENTRAL}:8443/job/${GIT_PROJECT}Dev/build?token=hunfihunfihunfi ;
    else
        curl -s -k -u anovak:Abcd1234 https://${SERVICES_CENTRAL}:8443/job/${GIT_PROJECT}Dev'/build?token=hunfihunfihunfi&'delay=$BUILD_DELAY ;
    fi
}

function start_test_build() {

    GIT_PROJECT=$1
    BUILD_DELAY=$(curl -s http://${SERVICES_CENTRAL}:8000/GetDelay/$GIT_PROJECT | python3 -c "import sys, json; print(json.load(sys.stdin)['delay'])");
    echo "Post receive hook build delay $BUILD_DELAY" >> /tmp/ano_git_log;
    if [[ "$BUILD_DELAY" = "0" ]] ; then
        curl -s -k -u anovak:Abcd1234 https://${SERVICES_CENTRAL}:8443/job/${GIT_PROJECT}Test/build?token=hunfihunfihunfi ;
    else
        curl -s -k -u anovak:Abcd1234 https://${SERVICES_CENTRAL}:8443/job/${GIT_PROJECT}Test'/build?token=hunfihunfihunfi&'delay=$BUILD_DELAY ;
    fi
}

# is commit?
if [[ "$CLOB" =~ ^.*refs/heads/master.*$ ]] ; then
    echo "Post receive hook, commit, notify builder..." >> /tmp/ano_git_log

    #TARGET_REV=$(echo $CLOB | awk '{print $2}')
    start_build "Starbank"

# is test tag?
elif [[ "$CLOB" =~ refs/tags/db-ci-ready-for-test-.*$ ]] ; then
    #TARGET_PROJECT=$(echo $CLOB | perl -n -e '/refs\/tags\/db-ci-ready-for-test-(.*?)-(.*)/ && print $1')
    echo "Post receive hook: Test tag detected" >> /tmp/ano_git_log
    start_test_build "Starbank"
fi

echo "Post receive hook ------------- END -----------" >> /tmp/ano_git_log
