#!/bin/bash
/var/opt/gitlab/git-data/repositories/ano/csas-db-ci.git/hooks/update-gitlab "$@"
RET_STAT=$?
SERVICES_CENTRAL="172.17.0.1"
if [ $RET_STAT -eq 0 ] ; then
  echo "Update hook start: $1 $2 $3" >> /tmp/ano_git_log
  if [[ "$1" =~ refs/tags/db-ci-.* ]] ; then
      echo "Update hook, maybe protected: $1" >> /tmp/ano_git_log
      # refuse remove target is 00000000000000000000
      if [[ "$3" =~ ^0+$ ]] ; then
        echo "DB CI refusing change. Protected tag: $1"
        echo "Update hook ------- END ------- " >> /tmp/ano_git_log
        exit 1;
      fi

      # allow ready for test
      if [[ ! "$1" =~ refs/tags/db-ci-ready-for-test-.* ]] ; then
          # refuse; allow only Jenkins and ano for now
          if [[ ! "$GL_USERNAME" =~ "ano" && ! "$GL_USERNAME" =~ "jenkins" ]] ; then
            echo "DB CI refusing change. Access Control."
            echo "Update hook ------- END ------- " >> /tmp/ano_git_log
            exit 1;
          fi
      fi
  fi

  if [[ "$1" =~ ^.*refs/heads/master.*$ ]] ; then
      echo "Update hook commit event" >> /tmp/ano_git_log
      git show $3 2>&1 >> /tmp/ano_git_log
      COMMIT_ID=$(git show $3 | grep commit | head -1 | cut -d ' ' -f2)
      git show $3:configuration.yaml | python3 /var/opt/gitlab/git-data/repositories/ano/csas-db-ci.git/hooks/check_build.py "$3"
      #BUILD_STATUS=$(curl -s http://$SERVICES_CENTRAL:8000/CheckBuild/$COMMIT_ID/SBANKDEV2)
      BUILD_STATUS=$?
      echo "Update hook: $BUILD_STATUS" >> /tmp/ano_git_log
      if [ "$BUILD_STATUS" -ne 0 ] ; then
        echo "DB CI refusing change. $COMMIT_ID not tested"
        echo "Update hook ------- END ------- " >> /tmp/ano_git_log
        exit 1;
      fi
  fi

  #echo " --------------------------------- SET START -------------------------------------" >> /tmp/ano_git_log
  #set >> /tmp/ano_git_log
  #echo " --------------------------------- SET END ---------------------------------------" >> /tmp/ano_git_log

  #GIT_DIFF=$(git diff-tree --no-commit-id --name-status -r $2 $3)
  #echo "Update hook: $GIT_DIFF" >> /tmp/ano_git_log

  #ACCESS_CONTROL=$(echo $GIT_DIFF | python3 /var/opt/gitlab/git-data/repositories/ano/csas-db-ci.git/hooks/update-hook.py 2>&1)

  #if [ $? -ne 0 ] ; then
  #    echo $ACCESS_CONTROL | perl -n -e '/(Exception: .*)/ && print $1';

  #    echo "Update hook ------- END ------- " >> /tmp/ano_git_log
  #    exit 1;
  #fi

  echo "Update hook ------- END ------- " >> /tmp/ano_git_log
fi

exit $RET_STAT

  
